name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run tests with race detection
        run: |
          export GO111MODULE=off
          go test -v -race ./...

      - name: Run coverage tests
        run: |
          export GO111MODULE=off
          go test -v -cover ./...